Repository ScicraftLearn/Minelabs, pull requests merged in 2023-06, with the labels that each got.

#738 Added painting to lang files
  src/main/generated/assets/minelabs/lang/en_us.json
  src/main/generated/assets/minelabs/lang/nl_be.json
  src/main/generated/data/minelabs/loot_tables/lasertool/blocks/cracked_deepslate_bricks.json
  src/main/generated/data/minelabs/loot_tables/lasertool/blocks/moss_block.json
  src/main/generated/data/minelabs/loot_tables/lasertool/blocks/raw_iron_block.json
  src/main/generated/data/minelabs/loot_tables/lasertool/blocks/waxed_oxidized_cut_copper_slab.json
  src/main/resources/assets/minelabs/lang/en_us.static.json
  src/main/resources/assets/minelabs/lang/nl_be.static.json
  src/main/resources/assets/minelabs/lang/nl_nl.json
Labels: language

#756 Structurized Reborn update
  build.gradle
  gradle.properties
  src/main/java/be/minelabs/world/gen/VillageAdditions.java
  src/main/resources/data/minelabs/structures/village/desert_scientist_1.nbt
  src/main/resources/data/minelabs/structures/village/plains_scientist_1.nbt
  src/main/resources/data/minelabs/structures/village/savanna_scientist_1.nbt
  src/main/resources/data/minelabs/structures/village/snowy_scientist_1.nbt
  src/main/resources/data/minelabs/structures/village/snowy_scientist_2.nbt
  src/main/resources/data/minelabs/structures/village/taiga_scientist_1.nbt
  src/main/resources/data/minelabs/structures/village/taiga_scientist_2.nbt
Labels: villager

#755 Chemical Lore
  src/main/java/be/minelabs/item/items/GasPotion.java
  src/main/java/be/minelabs/item/reaction/CorrosiveReaction.java
  src/main/java/be/minelabs/item/reaction/DissolveReaction.java
  src/main/java/be/minelabs/item/reaction/ExplosiveReaction.java
  src/main/java/be/minelabs/item/reaction/ExtinguishReaction.java
  src/main/java/be/minelabs/item/reaction/FlammableReaction.java
  src/main/java/be/minelabs/item/reaction/PoisonousReaction.java
  src/main/java/be/minelabs/item/reaction/Reaction.java
  src/main/java/be/minelabs/science/Molecule.java
  src/main/resources/assets/minelabs/lang/en_us.static.json
Labels: chemic effect
